### ISSUE TITLE
[Request] Check if planetDefs.xml is corrupt

### ISSUE THREAD

**Issue by NillerMedDild** [Advanced-Rocketry/AdvancedRocketry#1510]
## Version of Advanced Rocketry
1.12.2-1.5.0-127-universal
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
LibVulpes-1.12.2-0.4.0-2-universal
## Crash report or log (if applicable)
Relevant snippet: https://gist.github.com/NillerMedDild/a4708c02f5cf39a862ed1a7b5597e4c1
Full log: https://gist.githubusercontent.com/KCtops100/768e8dcae922fb3bb76d95b2f72a37f8/raw/5aaba9960498a7f47f55ed07d25f42c9c85c2fb7/gistfile1.txt

## Description of the problem
The planetDefs.xml config file of worlds has a tendency to corrupt when worlds are closed incorrectly, for example if the PC shuts down unexpectedly, or Minecraft is closed with alt+F4.
I suggest try catching the `org.xml.sax.SAXParseException`, so worlds can actually be entered despite the file being corrupted.

It would ofcourse be preferable to fix the corruption. Why is the planetDefs.xml being written to in the first place? Shouldn't it only be written to on world creation?

**Comment by NillerMedDild** [comment]
I hope #1508 will fix this issue :)

**Comment by voidsong-dragonfly** [comment]
planetDefs.xml is written to because of the commands allowing users to change planets while ingame. We can't fix the corruption on load, that's not how it works - if it's corrupted, we don't know the data that was supposed to be there. So, like other files, planetDefs still need to be written to, and closing unexpectedly has always been a problem.
