### ISSUE TITLE
Add Compatability to Matter Overdrive: Legacy edition

### ISSUE THREAD

**Issue by questionablexx** [Advanced-Rocketry/AdvancedRocketry#1600]
**What do you think is missing or what do you think can be done better**
[Describe in detail what you want to see and how it makes the mod better]
Okay, so there is this really great mod, and its called Matter Overdrive: Legacy edition

I would like you to add compatibility to the android part of the mod. So if you [The Player] has become an android they don't need a food bar (When I tested the two mods for some reason when used together android players had a food bar). Another thing is when you are an android you should not need oxygen to live anywhere in space, they should also not be effected by a heavy atmosphere and gravity. Thank you for reading my suggestion!

**Comment by Gliese-832-c** [comment]
The food bar thing actually is because of Matter Overdrive itself. To get rid of it, you now need to get the zero calories upgrade from the android station. Besides that, I fully agree with this suggestion and would love to see it added into the game.

**Comment by Nyabloody** [comment]
I wish someone would really do a PR for this. A lot of other space mods have already done the integration with androids actually (ie: Galacticraft, WarpDrive, ExtraPlanets, etc...). It seems very trivial to do but sadly I don't have the knowledge in Java or how to make such compatiblity between 2 mods. Maybe someone could check those mods, since their code are available on github too and do the same for AdvRocketry?

**Comment by voidsong-dragonfly** [comment]
Matter Overdrive has not udpated in two years, and is not on 1.16. Closing due to old version.
