### ISSUE TITLE
My new feature thread

### ISSUE THREAD

**Issue by AGiLE-EaGLE1994** [Advanced-Rocketry/AdvancedRocketry#1602]
I came up with some ideas for extra planet types and some other things:
Here are a few planet types:

Carbon world: This is a world that is much like Saturn's moon Titan, with a thick but not-crushing atmosphere, liquid methane and oil on the surface, underground water lakes, and methane/oil rain.

Hot Jupiter: This is a gas giant planet that is extremely close to its sun, and you can mine iron vapor from them. Ships approaching a Hot Jupiter have to have heatshields and can only stay near the planet for a limited amount of time before they start heating up, with the blocks slowly subliminating after the shields break down.

Oceanic world: this is an ocean planet, plain and simple. It would have oceans resembling the ones from 1.13.

Chthonian worlds: these are planets which are the burnt and scorched cores of Gas Giants who had lost all or almost all of their atmosphere, with nether biomes and mobs rampant, however they can be slept in if you have a space suit or a bed in your ship. There would be lava, magma blocks, netherrack everywhere.

Postgaian world: An Earth-like planet where its biosphere is being lost and its oceans are evaporating because its sun is getting hotter. (This will be what Earth will be like around 500-700 million years from now)

Mesogaian world: Basically a world that is still in its prehistoric era, with large land-based and sea-based predators, hot climate, and slightly shorter days than normal, and a single supercontinent.

Eogaian world: An Earth-like world that is extremely young and is just developing photosynthesis and eukaryotic life. Earth  2 to 0.9 billion years ago was like this.
Carboniferous world: A world covered in vast rainforests, with heavy rain, hot climate, and nearly all the land covered in trees.

Orxonian world: This ties in with my More Atmosphere types request: Basically, this is an Earth-like planet which is excessively polluted, with its oceans becoming sewage sludge which cannot be swam in and that hurts you upon touching it. Its air is unbreathable without a space suit, water breathing potion, or at least a space suit helmet and oxygen tanks, and its atmospheric effects cannot be disabled through the standard oxygen config setting, but instead these planets have their own settings, so that you can disable the oxygen system for space stations and airless moons, but still die from the polluted atmosphere on these worlds. They would be filled with high tech cities which contain loot from any high-tech mods installed (Mekanism, ComputerCraft, OpenComputers, Galacticraft, AR itself, Voltz Engine, ICBM, etc.) and are filled with villagers wearing gasmasks. If you right click on the villager with shears, it removes their gasmask and drops it in your inventory, but the villager dies as a result of the pollution.

---
Other ideas: 
Independent space stations which orbit a star directly or even just sit out in space all on their own.
Specifying stations in Planet XML
Putting beds in rockets allows you to sleep inside the rocket

toggleable star lifespan which works on periods of 2 real-life months which I will call stratums. 
The lifespan of the star and how it does depends on the size, brightness and temperature of the star.
A star of size 100 with a brightness between 64 and 84 will live between 50 and 20 stratums, (100 and 40 real-life months),  a star of size 150 or more will  purely have its life length depend on what stage the star is in and its temperature.
Sunlike stars will slowly get brighter, after 6 stratums, a Sunlike star created when the world was generated will transform any planets distance 130 or closer that are Earth like into Postgaian worlds, and then into Venuslike worlds.
After 80% of a star's life is over, the star will start to die, for stars similar to the Sun,  orange dwarfs or F dwarfs, they will turn into red giants for 3 stratums and turn any earthlike planets in the habitable zone into Chthonian worlds When the giant explodes it becomes a planetary nebula and then once the nebula fades it becomes a white dwarf.
For stars between sizes 150 and 220, they will explode into a Supernova which lasts 1 real-world week when they die, and leave behind a white dwarf.
Stars between sizes 221 and 500 will produce neutron stars after they blow up instead of white dwarfs.
Stars size 501 or higher will produce black holes instead.
Red dwarfs or stars size 49 or smaller will live for 1000 stratums, and after 80% of their life is through, they will turn into blue dwarfs, which will increase their brightness and move the habitable zone outwards but not increase the star's size. After that, they collapse into a white dwarf with no explosion.
Star aging and death can be enabled and disabled either for ALL Stars in config, or individual stars in the XML file can be given immortality in their settings where they will not age.

*Landing warp ships on planets

*Battles between warp ships

*Flyable starfighters with mini-warp cores

*Turbolasers that you can mount on space stations and warp ships which have the ability to destroy planets, stars and other warp ships/stations but use Dilithium as fuel

*procedurally generated warp ships, and space stations with Villagers that can be interacted with 

*Separate galaxies and universes of which you can have multiple.
Planets in every other universe are counterparts to the first universe, so the seeds for each counterpart planet will be the same, but the biomes, grass, ocean and surface blocks can be different, as can the atmosphere, cloud and fog color, sun size, brightness, temperature, and the planet's name and day length, but it must have the same number of moons. The counterpart planet's gravity can also be different, but ores will generate in the same area that they would on the version of the planet from the first universe.

----
More star types:
Supernova: These stars will burn the heck out of any planets orbiting them, there will be radiation everywhere, these stars would have a unique icon and would deal damage to any ships and stations in the nova's system unless the ship/system has a gamma shield or heat shield.
Flare star: These stars are rowdy and will flare up every 11 in game days, setting fire to anything within the habitable zone.

**Comment by C1ffisme** [comment]
> Carbon world: This is a world that is much like Saturn's moon Titan, with a thick but not-crushing atmosphere, liquid methane, and oil on the surface, underground water lakes, and methane/oil rain.

That's um... That's not what a [Carbon World](https://en.wikipedia.org/wiki/Carbon_planet) is. In fact, it'd probably be more accurate to call Titan a "Hydrocarbon World", but the reason we may call an exoplanet a "Carbon Planet" is because its composition contains more Carbon than Iron or Silicates.

https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Titan_poster.svg/800px-Titan_poster.svg.png

Titan actually has a silicate core and is somewhat like Europa in that it has an ocean, covered by a layer of ice, covered by another surface layer.

> Oceanic world: this is an ocean planet, plain and simple. It would have oceans resembling the ones from 1.13.

This is actually already somewhat possible by creating a world with only Deep Oceans and raising the sea level as high as you need, albeit on a real ocean world you would be unlikely to find the bottom for several kilometers. I suppose this kind of planet could use an icon, though.


As for the rest of the planet ideas, no problems as far as I see.


> toggleable star lifespan which works on periods of 2 real-life months which I will call stratums.

I'm not sure I like this idea. In singleplayer, this feature is invisible to the player and might not affect him besides one or two stars going kaboom. (Which is admittedly similar to real life, where the age of stars probably won't affect us besides some nice explosions hundreds of light years away.)

In multiplayer, however, the feature limits how long you can enjoy your world before every planet becomes either a charred husk or a cold, frozen snowball. I can see where this might be fun if you're playing with a small group of people and you like the idea of moving from planet to planet as stars die out, but even then, 40 months is a long time to wait.

What I foresee happening is that you'd have a multiplayer server where [optimistically] a bunch of players enjoy a year or so of playing together, then they end up logging off and a new group of people play on the server, all the while the stars barely bother any of the players. 

After 3-8 years, (the length of 40 to 100 months) if the server is still being hosted, the Overworld's sun will expand, the Overworld becomes a charred husk and new players don't want to play in the server anymore because all of the habitable nice planets are gone.

(Also worth noting, you specifically said that red dwarfs would last 166 real-life years. Why not just make them last forever instead of having the game check a timer that will almost undoubtedly never reach 166 real-life years?)

Now, maybe there's a compromise here: instead, let the player set an optional timer for how many real-life days until a star expands or supernovas. This would let adventure map creators and server owners choose how long they want to play on the same planet before they have to move to Pluto.

(It's worth noting that a lot of chunk updates would be required to turn say, an ice world into a water world. Now, if Minecraft stored block data by only storing what blocks in an area changed rather than all naturally generated blocks in an area, that'd make this a bit easier, but with Minecraft's current design it seems like this would be pretty heavy on a server.)

**Comment by AGiLE-EaGLE1994** [comment]
Thanks for the criticism and help with my ideas.
Here's a few more: 
Turrets on warp ships
* Being able to fly between two stations orbiting the same planet with a Flan' Mod plane
* Being able to have rockets drop landers, rovers or probes  which are made of blocks instead of the rocket all being one piece
* Multi stage rockets
*Being able to launch satellites, gas collection drones, station segments and other payloads using a Flan's Mod plane which contains the line "IsShuttle True" in its config file. (This ties in with my idea of Flans Mod planes being able to access the planet selection GUI by flying above Y-1000 if the plane is labelled as a spaceship in its config document. The plane can only fly into space when its inventory contains dilithium, plus a planet selector, or a planet selector and warp core. (Not the warp core multi-block structure, just the core block for it that has the block ID Warp Core). Warp cores in the inventory with a planet selector would allow the plane to travel to other planets and star systems, but just a planet selector alone would allow flight within the system the plane was launched from.
*Being able to launch Flan's Mod planes as rocket payloads

**Comment by voidsong-dragonfly** [comment]
Everything within this issue is either referenced somewhere else or not happening or already implemented.

Closing this issue because of this.
