### ISSUE TITLE
[Offer] New planet images

### ISSUE THREAD

**Issue by Golrith** [Advanced-Rocketry/AdvancedRocketry#1617]
**What do you think is missing or what do you think can be done better**
I made some new textures for the planets, feel free to use them.

![lava](https://user-images.githubusercontent.com/41104391/60461271-fcd0ef00-9c3d-11e9-9d33-a5ce2b02742d.png)
![marslike](https://user-images.githubusercontent.com/41104391/60461272-fcd0ef00-9c3d-11e9-96d6-ea5151da0a4f.png)
![moon](https://user-images.githubusercontent.com/41104391/60461273-fd698580-9c3d-11e9-8fe4-ec1f011e208b.png)
![shadow](https://user-images.githubusercontent.com/41104391/60461275-fd698580-9c3d-11e9-8b9a-f330363b87b9.png)
![atmosphere2](https://user-images.githubusercontent.com/41104391/60461277-fe021c00-9c3d-11e9-8215-207ec6462edc.png)
![earthlike](https://user-images.githubusercontent.com/41104391/60461280-fe9ab280-9c3d-11e9-9b26-8ef6c815445b.png)
![gasgiantblue](https://user-images.githubusercontent.com/41104391/60461282-fe9ab280-9c3d-11e9-9a23-129fbde27fc2.png)
![gasgiantred](https://user-images.githubusercontent.com/41104391/60461284-ffcbdf80-9c3d-11e9-87dc-aeb38ac103b1.png)
![iceworld](https://user-images.githubusercontent.com/41104391/60461285-0195a300-9c3e-11e9-85e1-b4c057a44479.png)

**Comment by C1ffisme** [comment]
[Hey these look familiar](http://texturesforplanets.com/)

AFAIK I don't think the TexturesForPlanets crew has any restrictions on what you can use their software for, but can you at least link to their website next time?

**Comment by Golrith** [comment]
Ah, sorry, should have mentioned that yes, I used that software as a foundation, then photoshopped them a bit to adjust the colour balance to work better with Minecraft's day/night sky.

Interesting fact, the code behind the planet generation I had actually played around with 20 years ago in Visual Basic, they've taken the core system behind it, and enhanced it with modern tech improvements.

**Comment by C1ffisme** [comment]
Wait, really? Now I wanna know more...

**Comment by Golrith** [comment]
Don't have the program available now (actually, it was 10-15 years ago..), I remember it worked with a lot of overlapping curves, which builds up the terrain and deals with spherical distortion on a 2D image. The version I saw produced a nice image, but when randomising them, they were pretty much the same and colour scheme was limited. TextureForPlanets crew have enhanced this method with the overlaying craters, cracks, etc.  

But, I did find a program I was writing to make a texture image. Couldn't get my head around the spherical maths, but got some good results:

![PlanetMap](https://user-images.githubusercontent.com/41104391/60616953-86152c80-9dca-11e9-8de5-b8d547614adf.jpg)

Each colour is a biome, calculated based on temperature and atmosphere pressure (at each pixel). My eventual goal was to put this code into a 4X space game for dynamic rendered planets.

**Comment by C1ffisme** [comment]
Dang, nice!

**Comment by zmaster587** [comment]
Unfortunately since there does not appear to be any notice explicitly saying that anything generated with the software is free to use, under US copyright law I cannot use it or anything derived from it without straying into murky legal waters.

The website does have a blurb about the program itself being free, but that doesn't mean that derivative works are free in legal terms.

**Comment by C1ffisme** [comment]
I decided to send them an email at info@texturesforplanets.com, but I'm not sure if the developer(s) still maintain their website, considering their last blog post was in 2015.

**Comment by MrEyeballs29** [comment]
That means it's **NOT** copyrighted.

**Comment by DVorriose** [comment]
I know these (and planets already in game) are simple images, but is there a way to dynamically shadow them?  Right now, we can have a crescent moon/planet above/below the sun, but lit from the wrong side.

**Comment by C1ffisme** [comment]
I got an email from info@texturesforplanets.com, despite not thinking I would get a response. Sadly they've just restated that we can use the textures "as we see fit":

![Screenshot_20190901_201014](https://user-images.githubusercontent.com/9893266/64084854-d8a09580-ccf4-11e9-846d-46e0634da266.png)

I've replied asking for more formal legal documentation.

**Comment by Archilyte** [comment]
i think [this](https://github.com/zmaster587/AdvancedRocketry/issues/1637) sounds like a better idea

**Comment by Deliphin** [comment]
@C1ffisme You seem to be misunderstanding US law. These people are explicitly giving you permission. You don't need a specific license from them.

Unless they give you a license that restricts you, "free to use" is as unlimited as the MIT license. If you were making a commercial product that was exclusively sold for money, you might have reason to get direct permission, but you've already gotten that via email, you're legally in the clear even to sell stuff from their program. You've seen a license that says free to use, and went out of your way to verify any restrictions, no judge is going to rule against you on this.

Not to mention, in US law, copyright leans on the accuser going out of their way to find copyright infringers. Nobody is going to chase after you, because the only people with the legal right to, have given you their explicit permission.

**Comment by C1ffisme** [comment]
@Deliphin 

> You seem to be misunderstanding US law.

Don't worry, I don't claim to be an expert, I just prefer being thorough and playing it safe.

**Comment by voidsong-dragonfly** [comment]
These are much higher res than the current ones, especially with the current res-lowering, and would seem extremely out of place in MC. current size is something like 128x128.
