### ISSUE TITLE
[Request] Artifical Planets

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [Advanced-Rocketry/AdvancedRocketry#1625]
**What do you think is missing or what do you think can be done better**
Someone on my server had the idea to build a custom planet. Could you make this possble to let someone create a planet using **massive** amount of resources? Theese planets should be very customizable (terrain, biomes, atmosphere, gravity, ...) and they should not have ores.

**Comment by zmaster587** [comment]
It's possible, yeah.  Though if i do something like that I might opt for mini planets instead.  Something like a 4096x4096 area.  Hmm....

**Comment by C1ffisme** [comment]
Worth noting that even a double chest full of sand/rocks is only 3456 cubic meters (which doesn't account for the compression that the core of our little planet would have), but using Wikipedia's statistics on dimensions:

- Phobos is about 1.1 x 10¹³ cubic meters
- Eros, an asteroid, is about 4.3 x 10¹² cubic meters
- Deimos is about 2.0 x 10¹² cubic meters

This is a little bit misleading though since this assumes that these dimensions refer to a cube with the length, height and width measurements defined by Wikipedia. Maybe mass is a better way to go about this?

Well, limestone (the rock a lot of people assume Minecraft's cobblestone is) weighs anywhere from 2160-2560 kg per cubic meter. Averaging this amount gets us 2360 kg. Therefore a double chest filled with smooth stone should have a mass of about 8.16 million kg or 8.15 x 10⁶.

- Phobos weighs about 1.0659×10¹⁶ kg
- Eros weighs about 6.687×10¹⁵ kg
- Deimos weighs about 1.4762×10¹⁵ kg

Maybe we should go the reverse way. How many double chests would it require to build Deimos in Minecraft?

1.47x10¹⁵ kg * (1 cobble/2360 kg) = 6.23x10¹¹ stone blocks
6.23x10¹¹ stone * (1 double chest/3456 stone) = 1.80x10⁸ double chests of stone

This... is not good.

That being said, we're talking about modded Minecraft, and in 1.12! Surely we can do better than a double chest.

A shulker box can store 1728 blocks of stone. If we put a shulker box of stone in every slot in a double chest, we can fit 93312 blocks of stone in that double chest.

6.23x10¹¹ stone * (1 shulker double chest/93312 stone) = 6.68x10⁶ shulker double chests, or about 6 and a half million.

Extra Utilities allows us to compress stuff like cobble and sand down into single blocks which contain 9, 81, 729, 6561, 59049, 531441, 4782969 and 43046721 blocks of cobble.

Let's say we're stuffing Octuple-compressed blocks of cobblestone into these shulker double chests: now instead of storing 93312 blocks of stone in each double chest, we're storing 4.02*10¹² blocks of cobble in each double chest.

6.23x10¹¹ cobblestone * (1 really well-built chest/4.02x10¹²) = 0.155 really well-built chests, or about 8 of the shulker boxes.

Now we're talking! Of course, 4.02x10¹² blocks of stone would fill up 61.6 million chunks, but this is only a tiny fraction of an entire Minecraft world, so if the player had an invincible golden pickaxe (which mines smooth stone at 5 blocks/second), they could mine all of that stone in just under 25500 Earth years! (804 billion seconds)


That being said, how big can we build with these Shulker Double Chests of Octuple-Compressed Cobblestone?

Every double chest would weigh 9.48x10¹⁵ kg using that 2360 block/kg figure from earlier. With that much stone, you could almost build Phobos (1.0659×10¹⁶ kg)

- With ten of them (about 10¹⁷ for simplicity purposes), you could almost build [Pandora](https://en.wikipedia.org/wiki/Pandora_(moon))
- With 100 of them, you could almost build [Thetis](https://en.wikipedia.org/wiki/17_Thetis).
- With 1000 of them, you could likely build [Helio](https://en.wikipedia.org/wiki/895_Helio)
- With 10000 (10²⁰ kg) of them, you could build [Enceladus](https://en.wikipedia.org/wiki/Enceladus) or [Miranda](https://en.wikipedia.org/wiki/Miranda_(moon)) which are both round!
- With 100000 of them, you can build Ceres. We've finally reached something that can be classified as a dwarf planet.
- With 130000 of them, you can build Pluto.
- With 730000 of them, you can build the Moon.
- With 3330000 of them, you can build Mercury. You might want to leave some of the blocks compressed since Mercury has a very dense metal core.
- With 6410000 of them, you can build Mars
- With 48680000 of them, you can build Venus
- With 59730000 of them, you can build the Earth

And with that, I think you get the point that building a planet is going to take at minimum millions and billions of years of playtime mining up stone. Even the most powerful Minecraft mods have not simulated anything close to what would be required to build even a small moon in Minecraft.

Maybe a more realistic way to go about this would be to collide "asteroids" that already contain quite a bit of mass instead. Sure, this would take massive amounts of fuel to pull off in the real world, but supposing we have magic engines that run extremely efficiently on solar power, maybe we could push around 10 Helio-sized asteroids to build a small moon like Enceladus.


To conclude: we're not exactly building artificial planets in the real world any time soon.

**Comment by DVorriose** [comment]
For mini-planets:

Making an asteroid/planetoid Galacticraft style shouldn't be hard, but not exactly a new concept.

Making an asteroid /planetoid starminer style seems hard( though cool), and not a new concept.  Not sure anyone would want go to that route.

What about a "world boarder" without a boarder, where in 1000m x 1000m, if you walk off +500 +500, you walk into -500 -500?  I failed at coding, so not sure if easy to implement or not.  Seems like terrain transition might be rough, even if all one biome.

It's something that might fit into, or even update (if buildable) planetDefs.xml

**Comment by Trip-SudoWudo** [comment]
Perhaps creating something like GLASS or World Portals could help with the visuals? AFAIK the teleporting should be easy

**Comment by AGiLE-EaGLE1994** [comment]
I'd prefer StarMiner style mini planets.

**Comment by voidsong-dragonfly** [comment]
Not happening
