### ISSUE TITLE
Give titanium a grey color, like in real life

### ISSUE THREAD

**Issue by Gliese-832-c** [Advanced-Rocketry/AdvancedRocketry#1739]
Titanium should not be purple.

Here is a picture I found on Wikipedia: 
![grafik](https://user-images.githubusercontent.com/55159077/70177728-34efc880-16db-11ea-870a-ffd4571ae555.png)

Titanium should be a greyish silver color. Some people might argue that it will be too hard to differentiate from iron, but to mitigate that, it could have a slightly different near-grey tint, like, maybe a bit lighter.

**Comment by MrEyeballs29** [comment]
"Gray". Not grey.

**Comment by Gliese-832-c** [comment]
@MrEyeballs29 Grey is british English you traitor colonies.

**Comment by MrEyeballs29** [comment]
You're calling me a traitor. How unGRAYteful you are. That besides the point, titanium doesn't need gray color because there might be too many grayscale metals including iron, tin, and steel. Still using "A" in gray.

**Comment by C1ffisme** [comment]
~~No tax**ay**tion without represent**ay**tion~~

Have to agree with MrEyeballs. Iron, Tin, Chromium, Silver, Platinum, Nickel, Cobalt, Aluminum, Zinc, even metals like Lead or Uranium are actually grey. Really most metals not named "Copper" or "Gold" are only colorful if they're an oxide.

In order to solve this issue, the only solutions are:
A: A brighter or darker grey
B: Colors

The problem with option A is that after a while you run out of shades of g- I mean colors between black and white. It's also just not that fun to look at. That's why non-grey colors exist!

That being said, I do think the titanium could be desaturated a bit. It looks like some kind of alien metal right now.

**Comment by Divineaspect** [comment]
If you want a scientific approach, just make an RGB map for the element from it's spectral lines, then it's scientific, and we can just fudge Steve/Alex being able to see more colors.

**Comment by NutMaster6942** [comment]
> Titanium should not be purple.
> 
> Here is a picture I found on Wikipedia:
> ![grafik](https://user-images.githubusercontent.com/55159077/70177728-34efc880-16db-11ea-870a-ffd4571ae555.png)
> 
> Titanium should be a greyish silver color. Some people might argue that it will be too hard to differentiate from iron, but to mitigate that, it could have a slightly different near-grey tint, like, maybe a bit lighter.

Like C1ffisme said, most metals are gray. This would cause problems if we tried to make all metals look realistic, we would run out of grays.

**Comment by MrEyeballs29** [comment]
Thank you @NutMaster6942 for calling gray with an "A", not "E." Besides that, the metals might be confusing because their grayscale contrast would be too similar.

**Comment by NutMaster6942** [comment]
> Thank you @NutMaster6942 for calling gray with an "A", not "E." Besides that, the metals might be confusing because their grayscale contrast would be too similar.

You're welcome, I guess. We spell it "grey" here though.

**Comment by Silfryi** [comment]
How does `0xccc8fa` look? It's about as desaturated as I'd want to go.

**Comment by voidsong-dragonfly** [comment]
Titanium color has changed in newest LV
