### ISSUE TITLE
Satellite-indepentent data collection method for space stations

### ISSUE THREAD

**Issue by Gliese-832-c** [Advanced-Rocketry/AdvancedRocketry#1741]
Instead of having to launch a satellite, you should be able to collect the data required to scan for an asteroid on a space ship. To make it balanced and encoure satellite use, maybe make it a big expensive multiblock which requires tons of iridium.

**Comment by MrEyeballs29** [comment]
Again, the use of that really high end metal. The multi block should be made of steel or even aluminum.

**Comment by C1ffisme** [comment]
I know that this is modded Minecraft and all, but why make something cost a crapton of extremely expensive metal in order to encourage something else? Why must everything come down to either a grind or an incredibly expensive automatic mining machine that also probably cost a lot of grinding? Couldn't you just add additional benefits to the thing we're trying to incentivize or require a lot of a very common metal/just a little bit of the rare metal?

In addition to that, why should using an asteroid scanner on a spacecraft cost more than an asteroid scanner on a satellite? I know that sometimes balance overrides logic but that doesn't make sense. Heck, it doesn't even make sense from a balancing perspective: why _should_ we use satellites over regular spacecraft?

**Comment by voidsong-dragonfly** [comment]
No. Use satellites, you should be able to connect to them within the planetary system and there is no reason to usurp the satellite system with something that people will entirely use more than them because it's visible and seemingly more approachable and the sats are not.
