### ISSUE TITLE
[Request] A way to combine stations

### ISSUE THREAD

**Issue by Eagle1128** [Advanced-Rocketry/AdvancedRocketry#1786]
So while playing with a few friends, we started thinking it would be convenient to combine our stations. I think it would be interesting if we were able to combine stations in the same orbit. I’m not sure how it would work.

We actually got the idea after watching the 100, how the Ark station was previously twelve separate stations, but were combined.

As a way to make sure the game doesn’t break, if any player is on a station being connected to another, they will be transported to the dimension where the “parent” station is.

**Comment by Silfryi** [comment]
What do you mean by connected?

**Comment by Eagle1128** [comment]
By connected I mean like linking two space stations together in one area to become one station.

**Comment by Silfryi** [comment]
(Sorry for the late reply) This is essentially impossible because of how Minecraft and space stations work. Moving an entire station with possible TEs and other blocks to a whole other location can cause world corruption and other problems (in the case of TEs, which stations are essentially always going to have).
