### ISSUE TITLE
using holo projector crashes player client on server

### ISSUE THREAD

**Issue by YawningRaptor76** [Advanced-Rocketry/AdvancedRocketry#1871]
## Version of Advanced Rocketry
1.7.10-1.0.19 beta
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
1.7.10-0.2.8-27
## Version of Minecraft
1.7.10
## Crash report or log (if applicable)
https://pastebin.com/2g13MLVK

## Description of the problem
mod files loaded onto apexhosting server using holo projector the player client game would crash and they cant join unless you teleport player through console and relocate hologram location just to teleport player back were they were because it would crash again

**Comment by Stadtplaner1988** [comment]
I had the same problem.

**Comment by Silfryi** [comment]
Okay, there are SO many problems with this issue. First of all, that AR version is extremely old. Update to the latest AR alpha out for that version, it'll be much more stable and have many more features. Secondly, you're on 1.7.10 and we offer no support to 1.7.10, regardless of version. This query has hit a dead end if it's not fixed by updating your AR version.
