### ISSUE TITLE
(Request) Advanced rocketry series/Advertisement stuff

### ISSUE THREAD

**Issue by ghost** [Advanced-Rocketry/AdvancedRocketry#196]
I've been looking on YouTube and there aren't really any videos about Advanced rocketry, there's like only a few videos of it, information on the mod is also kinda sparse, and there isn't really any info on new updates. Maybe someone could make a series on Advanced rocketry and what it's planets are like?. I also don't think anyone's really heard of it, i think making an Advanced rocketry series (and possibly some form of advertising on minecraft forums) will make it more popular and attract more supporters and coders.

**Comment by zmaster587** [comment]
That would be nice, I've been desperate for help with the documentation as of late, I'm trying to get a documentation website up and up to date at http://65.78.115.159:8000/AdvancedRocketry/ but it takes a lot of time.

**Comment by Tronzoid** [comment]
Nice, this mod is dying for information and vids

**Comment by zmaster587** [comment]
If you or anyone would like to help the repo is here: https://github.com/zmaster587/AdvancedRocketryDoc

**Comment by TheGuyRunningSouth** [comment]
I'm down with doing a series on AR. I was planning on it anyway but was waiting until it was in a fairly stable state and I figured out how to work everything.

**Comment by bludde** [comment]
i will have a RP server for some friends that has AR as main mod. Will be some videos on that up soon:)

**Comment by TheGuyRunningSouth** [comment]
Come to think of it, if @zmaster587 thinks it would help, I can make one or more mod spotlight videos on the different parts of AR.

**Comment by zmaster587** [comment]
I would really appriciate all of that, I'm only planning on 2 more content builds for 1.7.10, anything after that will only be bug fixes.  And them I'm going to move to 1.10.  So thing should start to stabilize soon.

**Comment by TheGuyRunningSouth** [comment]
Cool. Also, how exactly do you use the ADP? Any time I stick an asteroid
chip in it to play with it it immediately eats my chip.

**Comment by zmaster587** [comment]
are you putting in in the input hatch or in the interface?  If you put an unprogrammed chip into the input hatch or the top left slot it'll program it then put it into the output slot.  This will yeild a chip that is programmed but has no data.  To put data into the chip you need to put it into the input slot or the bottom left slot and put Composition data, Distance data, and mass data into the appropriate data busses.  Then flip all the switches into the ADB and let it program data into the chip until it's either full or has the desired amount of data, if it is full of all three types it is automatically ejected into the output slot, then it is ready to use in the rocket.

**Comment by TheGuyRunningSouth** [comment]
So, I've been trying to figure out how to handle a spotlight, and I've come to the conclusion that a multi-part spotlight would be best, in order to feature all of AR's functionality.

I've been thinking something along the lines of:

-  Multiblock Machines (Functionality, b/c holoprojector handles construction so well).
- Satellites/Data System/Mining
- Rocket Construction/Launching
- Space Stations/Warp Ships
- Space Suit
- Misc (things that didn't fit elsewhere)

That being said, I have two questions.

1. What order should users be introduced to the mod in?
2. Does AR have a defined end goal/what are users working towards? With the revamp of the data system, is it asteroid mining, terraforming, etc.?

**Comment by Tronzoid** [comment]
Users should be introduced to the starting blocks and items, then it should move onto stuff like shipbuilding and data collection .etc

**Comment by TheGuyRunningSouth** [comment]
I agree with you on the concept, but what blocks/items/etc are we calling
"starting "? I don't want to throw too much at people at once, but I want
to make sure to cover it all.

**Comment by Tronzoid** [comment]
Stuff like the compressor, holoprojector, and the rocket assembly machine.

**Comment by Luckie21** [comment]
Im starting a youtube channel here in the next month or two and i would be more then happy to spotlights on advanced rocketry. I recently (and by recently i mean today) had a catastrophic pc meltdown and now limited to my laptop which is unable to run modded minecraft so thats why i cant start the channel for a month or two! but once i rebuilt that darn thing my ill create my channel and start uploading videos!

**Comment by Luckie21** [comment]
Im also starting college in January and will be taking everything to become a coder so after like 6 months under my belt of that and if @zmaster587 approves i could start help coding this mod. IM already a decent coder. just havent posted any of my work because my parents dont approve of where this coding is taking me!

**Comment by voidsong-dragonfly** [comment]
There are, at this point, a few large tutorials, and AR has gained popularity. We're good on the advertisement stuff.
