### ISSUE TITLE
electrical arc furnace don't work

### ISSUE THREAD

**Issue by Timbo10000** [Advanced-Rocketry/AdvancedRocketry#1986]
## Version of Advanced Rocketry
>AdvancedRocketry-1.12.2-1.7.0-235-universal

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-75-universal

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] Y

## Description of the problem
After a while playing the electrical arc furnace takes the ingots put dosen't put out anything

**Comment by Silfryi** [comment]
Does your log say anything? Which ingots? Does the furnace have enough power? Have you waited the full time (10 minutes for some ingots)? Your lack of verbosity gives me nothing to go by.

**Comment by MightBeAHuman** [comment]
I've got the same problem, with any kind of ingot, and it has got unlimited power because of my creative energy plug. In the GUI it shows me that it has got full power. After a while, the furnace just extinguishes itself without giving me the items back. Minecraft doesn't crash, I can keep playing like nothing happened.

I am using Minecraft 1.16.5, Forge 36.2.0, LibVulpes 1.16.5-1.0.2-27 and Advanced Rocketry Mod 1616.5-2.0.0-12

Log:
[latest.log](https://github.com/Advanced-Rocketry/AdvancedRocketry/files/7196748/latest.log)

List of all Mods in my Modpack:
[Modlist.txt](https://github.com/Advanced-Rocketry/AdvancedRocketry/files/7196776/Modlist.txt)

Images:
![image](https://user-images.githubusercontent.com/72646433/134026473-0d68dc8d-a838-4cbe-8a49-ed553420c30e.png)
![image](https://user-images.githubusercontent.com/72646433/134026502-c70560de-65e6-4794-87dc-adf34922403f.png)
![image](https://user-images.githubusercontent.com/72646433/134026556-4fad299e-890a-454a-a7b3-96320551d06f.png)

Can you please help me? Thank you!

**Comment by voidsong-dragonfly** [comment]
This issue is not even for the _version_ you are on. Bug off and go open a new issue if you need to, commenting on old, _closed_ issues helps no one.
