### ISSUE TITLE
[enhancement] Decoupling and 2 engine types

### ISSUE THREAD

**Issue by Jummit** [Advanced-Rocketry/AdvancedRocketry#847]
Do you know this staging thing in Kerbal space program? You decouple engines and fuel tanks. There are two type of engines:
# Solid fueled engines
they use fuel that is in the engine part, but very fast and ineffective. This is used to boost you're rocket at launch.
# Liquid fueled engines
they use fuel from tanks you added to the rocket, and that very slow, but effective. This is used to make maneuvers and fine controlls after boosting the rocket with the solid fuel engines.

Now there are decouplers. With them you can cut out burned engines from the rocket if you dont need them anymore.

# So, to wrap things up:
You're rocket looks like this: 
1. liquid engines with liquid fuel
2. Decoupler
3. Solid fueled engine
instead of this:
1. liquid engines with liquid fuel

The strength of the liquid fueled engines needs to decrease, and a new type of engine, the solid engine should be added, which are very strong but have a very short burst time.
When you build youre rocket you have to configure the decouplers and give them a number.
And decoupler should be added too. In flight you can press the number and all decouples with the number will decouple.

**Comment by EvilCooky** [comment]
This would make the rocets more realistic, but I see a few problems with that idea.

To allow your rocket to split, it needs to be buitl as multiple enteties that work together.
While not impossible, it is very complicated and a lot of work without much benefit.

This will make it impossible to reuse rockets. For eery launch you need to build another lower section for your rocket. this makes automating transport or mining rockets impossible.

**Comment by Jummit** [comment]
> To allow your rocket to split, it needs to be buitl as multiple enteties that work together.

But you can disassemble a rocket easy? I thought about make everything as usual, only that you save the hight of the decouplers and will disassemble the rocket, cut it, and assemble it again. Sounds easy to me?

**Comment by C1ffisme** [comment]
I would be very interested in KSP-style realistic rocketry, at least for the start of the player's Space Age. (Including basic aerodynamics, heat shielding, parachutes, rocket stages, and orbiting.)

The problem of reusing rockets is probably best solved by making more and more reusable rockets as the player progresses. For Example:

* At the start of the game, only the most primitive rocket engines and rocket fuel can be manufactured by default. This requires the player to build detachable rocket engines. The player can get to the Moon at this point, and space stations.

* A certain ore should spawn on every planet (including the moon) that isn't Earth by default. (Maybe dilithium?) This ore can be used to make newer machines, and those machines can make engines that don't need to be detached or more efficient fuel, however, neither can go on a rocket at the same time.

* Another ore will spawn on planets other than Earth or the Moon, and it can be used to make machines that allow for more efficient engines and fuel, neither of which need to be disposed of. (And possibly allowing for vertical liftoffs from a planet, like an aircraft. Imagine flying an X-Wing up to a space station... Awesome!)


Making a rocket into multiple entities doesn't sound hard at all. I don't know the code that would go into it, but I know it's possible to make entities like horses or minecarts carry other entities, including themselves, so that's a start.

Spacecraft may have to be limited to a certain few blocks that have certain significance in rocket building, though. That way weight and aerodynamics can be calculated by the Rocket Builder.

**Comment by voidsong-dragonfly** [comment]
This is covered by #214 & #316
